package pt.ipleiria.estg.dei.puzzlepets;

public enum TipoPoder {
	ARCO_IRIS, MOVIMENTO_EXTRA, PANDA_CRUZ, PANDA_ESTRELA, 
	PANDA_HORIZONTAL, PANDA_VERTICAL, PEIXE_CRUZ, PEIXE_ESTRELA, 
	PEIXE_HORIZONTAL, PEIXE_VERTICAL, POLVO_CRUZ, POLVO_ESTRELA, 
	POLVO_HORIZONTAL, POLVO_VERTICAL, SAPO_CRUZ, SAPO_ESTRELA, 
	SAPO_HORIZONTAL, SAPO_VERTICAL

}
